/*
 * URL Collector API
 *
 * API for URL Collector
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type Pictures struct {
	Urls []string `json:"urls"`
}
